general:
    input_image_dir: '/home/sizhuo/Desktop/code_repository/treePoints/test_example/'
    input_image_type: '.tif'  # '.tif'#'.jp2'
    input_image_pref: ''  # prefix of image file names, can be used to filter out images
    channel_names1:
        - 'red'
        - 'green'
        - 'blue'
        - 'infrared'
    channels:   # to take color bands in the correct order (match with the model)
        - 0
        - 1
        - 2
        - 3
    output_dir: '/home/sizhuo/Desktop/code_repository/treePoints/test_example/preds/'
    output_suffix_seg: '_seg' # for segmentation
    output_suffix_density: '_density' # for density
    output_image_type: '.tif'
    output_prefix: 'pred_'
    overwrite_analysed_files: False
    output_dtype_seg: 'uint8'
    output_dtype_density: 'float32'

#    cuda_device_id: 0 # to add


predict:
    model_save_path: '/home/sizhuo/Downloads/project_test/saved_models/'
    fillmiss: 0 # only fill in missing preds
    segcountpred: 1 # whether predict for segcount
    normalize: 1 # patch norm
    multires: 0
    saveresult: 1
    input_size: 256 # model input size
    inputBN: False
    threshold: 0.5
    BATCH_SIZE: 112 # Depends upon GPU memory and WIDTH and HEIGHT
    WIDTH: 256 # crop size
    HEIGHT: 256
    STRIDE: 64 #224 or 196   # STRIDE: WIDTH means no overlap, STRIDE: WIDTH/2 means 50 % overlap in prediction

postprocess:
    chm_dir: '/mnt/ssdc/Denmark/DK_treeProject_DHI_KDS/elevation/DHM/'
    elevation_dir: '/mnt/ssdc/Denmark/DK_treeProject_DHI_KDS/elevation/DTM/'
    min_dis: 10
    thres_abs: 0.0005
    alpha: 0.2
    height_window: 6
    scan_window: 15
    low_vege: 3
    ndvi_tree: 0
    num_peak_chm: 1000
    maxworker: 15




